---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - flux.gitops.pro
  resources:
  - gatedkustomizationdeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux.gitops.pro
  resources:
  - gatedkustomizationdeployers/finalizers
  verbs:
  - update
- apiGroups:
  - flux.gitops.pro
  resources:
  - gatedkustomizationdeployers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - flux.gitops.pro
  resources:
  - kustomizationautodeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux.gitops.pro
  resources:
  - kustomizationautodeployers/finalizers
  verbs:
  - update
- apiGroups:
  - flux.gitops.pro
  resources:
  - kustomizationautodeployers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - patch
  - update
  - watch
